
USE CEPEA_SAS

--1223

/*

DROP TABLE IF EXISTS #BASE
SELECT
    A.NR_CPF AS CPF,
    A.NR_DI AS DI,
       CONCAT(A.NR_CPF, A.NR_DI) AS CPF_DI ,
    A.CD_TIP_EVE,
    B.NM_TIP_EVE AS NM_TIP_EVE_JOIN,
    A.CD_EVE,
    C.NM_EVE AS NM_EVE_JOIN,
    A.TP_MOT_TRM,
    A.CD_EVE_TRM,
    D.CD_SIT_REG AS CD_SIT_REG_JOIN , -- A = ATIVO, E = EXCLUÍDO , F = falecido, 0 = erro, P CATEGORIA P, I = INATIVO, B = BLOQUEADO
       CASE
             WHEN D.CD_SIT_REG = 'A' THEN 'ATIVO'
             WHEN D.CD_SIT_REG = 'E' THEN 'EXCLUÍDO'
             WHEN D.CD_SIT_REG = 'F' THEN 'FALECIDO'
             WHEN D.CD_SIT_REG = '0' THEN 'ERRO'
             WHEN D.CD_SIT_REG = 'P' THEN 'CATEGORIA P'
             WHEN D.CD_SIT_REG = 'I' THEN 'INATIVO'
             WHEN D.CD_SIT_REG = 'B' THEN 'BLOQUEADO'
       ELSE D.CD_SIT_REG 
       END AS CD_SIT_REG_DESC ,
    A.ID_SIT_VINC,
    CONVERT(VARCHAR(10), TRY_CAST(A.DT_SIT_VINC AS DATE), 103) AS DT_SIT_VINC,
    CONVERT(VARCHAR(10), TRY_CAST(A.DT_INI_EXERC AS DATE), 103) AS DT_INI_EXERC,
    CONVERT(VARCHAR(10), TRY_CAST(A.DT_INI_VIG AS DATE), 103) AS DT_INI_VIG,
    CONVERT(VARCHAR(10), TRY_CAST(A.DT_FIM_VIG AS DATE), 103) AS DT_FIM_VIG,
    CONVERT(VARCHAR(10), TRY_CAST(A.DT_INI_VIG_EVE AS DATE), 103) AS DT_INI_VIG_EVE,
    CONVERT(VARCHAR(10), TRY_CAST(A.DT_FIM_VIG_EVE AS DATE), 103) AS DT_FIM_VIG_EVE,
    A.TP_ATO_OFIC_TRM,
    CONVERT(VARCHAR(10), TRY_CAST(A.DT_INIC_VIGEN_EVENT_TRM AS DATE), 103) AS DT_INIC_VIGEN_EVENT_TRM,
    CONVERT(VARCHAR(10), TRY_CAST(A.DT_FIM_VIGEN_EVENT_TRM AS DATE), 103) AS DT_FIM_VIGEN_EVENT_TRM, 
    CONVERT(VARCHAR(10), TRY_CAST(A.DT_POSSE AS DATE), 103) AS DT_POSSE,
    CONVERT(VARCHAR(10), TRY_CAST(A.DT_ULT_ALTER AS DATE), 103) AS DT_ULT_ALTER,
    A.CD_CARGO_FUNC_ATUAL,
    A.CD_CARGO_FUNC_EVE,
    A.ID_CARGO_FUNC,
    A.ID_CAT_FUNC,
    A.ID_ORI_CARGO_FUNC,
    A.CD_UNID_ADM_CLASS,
    A.CD_UNID_ADM_EVE,
    A.CD_JORN_ANT,
    A.CD_JORN_ATU,
    A.CD_UNID_ESCOL_CLASSIF_TIT,
    A.CD_UNID_ESCOL_EVE,
    A.CD_TIP_PROV,
    A.FL_PROLABOR,
    A.TP_ATO_OFIC,
    A.ID_ORG_ATO_OFIC,
    A.NR_ATO_OFIC,
    A.NR_ANO_ATO_OFIC,
    CONVERT(VARCHAR(10), TRY_CAST(A.DT_PUBL_ATO_OFIC AS DATE), 103) AS DT_PUBL_ATO_OFIC, 
    A.ID_REF_FAIXA,
    A.ID_GRAU_NIV,
    A.QT_HORA_CARGA_SUPL,
    A.NR_RG_SUBST,
    A.CD_MOT_SUBST,
    A.ID_LOCAL_AFAST,
    A.NM_LOCAL_AFAST,
    A.CD_ACUM_CARGO_1,
    A.TP_ACUM_CARGO_1,
    A.NR_PAREC_COMIS_ACUM_CARGO_1,
    A.NR_ANO_PAREC_ACUM_CARGO_1,
    CONVERT(VARCHAR(10), TRY_CAST(A.DT_PUBL_ACUM_CARGO_1 AS DATE), 103) AS DT_PUBL_ACUM_CARGO_1,
    A.CD_REG_HABILIT,
    CONVERT(VARCHAR(10), TRY_CAST(A.DT_REG_HABILIT AS DATE), 103) AS DT_REG_HABILIT,
    A.CD_ORG_EMIS_REG,
    A.TP_ATO_OFIC_CES_EXER,
    A.ID_ORG_ATO_OFIC_CES_EXER,
    A.NR_ATO_OFIC_CES_EXER,
    A.NR_ANO_ATO_OFIC_CES_EXER,
    CONVERT(VARCHAR(10), TRY_CAST(A.DT_PUBL_ATO_OFIC_CES_EXER AS DATE), 103) AS DT_PUBL_ATO_OFIC_CES_EXER,
    A.CD_OPCAO_TRANS_UTIL,
    A.CD_TERMINAL,
    A.CD_OPER,
    CONVERT(VARCHAR(10), TRY_CAST(A.DT_ALTER AS DATE), 103) AS DT_ALTER,
    CONVERT(VARCHAR(10), TRY_CAST(A.DT_HORA_INIC_ALTER AS DATE), 103) AS DT_HORA_INIC_ALTER,
    CONVERT(VARCHAR(10), TRY_CAST(A.DT_HORA_FIM_ALTER AS DATE), 103) AS DT_HORA_FIM_ALTER,
    A.FL_FOLHA_PAGTO_HIST,
    A.ID_NUM_PROC_SAUDE,
    A.NR_ANO_PROC_SAUDE,
    A.TP_TEMPO_SIT_ESPEC,
    CONVERT(VARCHAR(10), TRY_CAST(A.DT_PUBL_2 AS DATE), 103) AS DT_PUBL_2, 
    A.NR_PROC,
    A.ID_ORG_EMIS_PROC,
    A.NR_ANO_PROC,
    A.ACAO_JUDICIAL,
    CONVERT(VARCHAR(10), TRY_CAST(A.DT_ULT_ATUALIZ AS DATE), 103) AS DT_ULT_ATUALIZ,
    A.ID_ORG_ATO_OFIC_TRM,
    A.NR_ATO_OFIC_TRM,
    A.NR_ANO_ATO_OFIC_TRM,
    CONVERT(VARCHAR(10), TRY_CAST(A.DT_PUBL_ATO_OFIC_TRM AS DATE), 103) AS DT_PUBL_ATO_OFIC_TRM, 
    A.CD_UNID_ADM_EVE_TRM,
    A.CD_CARGO_FUNC_EVE_TRM,
    A.FL_PROC_QUEBRA,
    A.CD_CARGO_FUNCAO_ATUAL_TRM,
    A.CD_UNID_ADM_CLASSIF_TRM,
    A.CD_JORN_ANT_TRM,
    A.CD_JORN_ATUAL_TRM,
    A.CD_UNID_ESCOL_CLASSIF_TITUL_TRM,
    A.CD_UNID_ESCOL_EVENT_TRM,
    A.CD_TP_PROV_TRM,
    A.FL_PROLABOR_TRM,
    CONVERT(VARCHAR(10), TRY_CAST(A.DT_POSSE_TRM AS DATE), 103) AS DT_POSSE_TRM,
    CONVERT(VARCHAR(10), TRY_CAST(A.DT_INIC_EXERC_TRM AS DATE), 103) AS DT_INIC_EXERC_TRM,
    A.ID_SIT_VINC_TRM,
    CONVERT(VARCHAR(10), TRY_CAST(A.DT_SIT_VINC_TRM AS DATE), 103) AS DT_SIT_VINC_TRM,
    A.ID_REF_FAIXA_TRM,
    A.ID_GRAU_NIVEL_TRM,
    A.ID_CARGO_FUNCAO_TRM,
    A.ID_CATEG_FUNCIO_TRM,
    A.ID_ORIG_CARGO_FUNCAO_TRM,
    A.QTD_HR_CARGA_SUPL_TRM,
    A.NR_RG_SUBST_TRM,
    A.CD_CARGO_FUNCAO_TRM,
    A.TP_EVOL_EVENT,
    A.TP_DOC_EVENT,
    CONVERT(VARCHAR(10), TRY_CAST(A.DT_PEDIDO_CERTIF_EVENT AS DATE), 103) AS DT_PEDIDO_CERTIF_EVENT, 
    A.NR_ATO_ACAO_JUDICIAL,
    A.NR_RG,
    A.FL_FOLHA_PAGTO,
    A.[SYS_C00079_14093022:06:13$]
INTO #BASE
FROM CONTAGEH.dbo.TB_ATRIB_EVENTO A
LEFT JOIN CONTAGEH.dbo.TB_TIPO_EVENTO B ON A.CD_TIP_EVE = B.CD_TIP_EVE
LEFT JOIN CONTAGEH.dbo.TB_EVENTO C ON A.CD_EVE = C.CD_EVE AND A.CD_TIP_EVE = C.CD_TIP_EVE
LEFT JOIN CONTAGEH.[dbo].[TB_FUNCIONAL] D ON A.NR_CPF = D.NR_CPF
--WHERE D.CD_SIT_REG = 'A' -- A = ATIVO, E = EXCLUÍDO , F = falecido, 0 = erro, P CATEGORIA P, I = INATIVO, B = BLOQUEADO
--AND A.CD_EVE = 'C'
--AND A.CD_TIP_EVE = 'CF'
--AND A.DT_FIM_VIG_EVE IS NULL

-- (2101 rows affected)

DROP TABLE IF EXISTS #CPFDI_EVENT
SELECT DISTINCT
   CPF,
   DI
INTO #CPFDI_EVENT
FROM #EVENTO

-- (2064 rows affected)

*/

SELECT 
   A.CPF,
   A.DI ,
   B.NOME       ,
   B.CARGO_C,
   B.CATEG_C,
   B.CARGO_E,
   B.CATEG_E
FROM #CPFDI_EVENT A
LEFT JOIN CTG0826 B ON A.CPF = B.CPF AND A.DI = B.DI


SELECT
      NR_CPF AS CPF               ,
      NR_DI AS DI                 ,
        CONCAT(NR_CPF, NR_DI) AS CPF_DI ,
      NR_RG AS RG                 ,
      CD_SIT_REG AS SITUACAO, -- A = ATIVO, E = EXCLUÍDO , F = falecido, 0 = erro, P CATEGORIA P, I = INATIVO, B = BLOQUEADO     ,
      DT_SIT                      ,
      NR_QUIN_ADIC_TS             ,
      DT_VIG_ULT_QUIN_ATS         ,
      CD_INDIC_SEXTAPARTE         ,
      DT_VIG_SEXTAPARTE           ,
      CD_CARGO_FUNC_TIT           ,
      CD_IDENT_CAT_FUNC_TIT AS CATEG_E,
      DT_POSSE_TIT                ,
      DT_INIC_EXERC_TIT           ,
      CD_CLASSE_DISC_TIT AS CLDISC,
      CD_IDENT_SIT_ESPEC_TIT AS SIT_ESP,
      DT_INIC_SIT_ESPEC_TIT AS DT_SIT_ESP,
      CD_IDENT_REF_FAIXA_TIT AS REF_FAIXA,
      CD_IDENT_GRAU_NIV_TIT AS GRAU_NIV,
      CD_JORNADA_TIT AS JORNADA   ,
      CD_UNID_ESC_CLASS_TIT AS CIE_C,
      CD_UNID_ADM_CLASS_TIT AS UA_C,
      CD_UNID_ESC_EXERC_TIT AS CIE_E,
      CD_UNID_ADM_EXERC_TIT AS UA_E,
      CD_TIP_INTERRUP_CESS_TIT AS INTERRUP,
      CD_MOT_INTERRUP_CESS_TIT AS MOT_INTERRUP,
      DT_INIC_INTERRUP_CESS_TIT AS DTI_INTERRUP,
      DT_FIM_INTERRUP_CESS_TIT AS DTF_INTERRUP,
      CD_MOT_AFAST_TIT AS MOTIAFAS,
      DT_INIC_AFAST_TIT AS DTI_MOTIAFAS,
      DT_FIM_AFAST_TIT AS DTF_MOTIAFAS,
      CD_MOT_LIC_TIT AS MOTILICE  ,
      DT_INIC_LIC_TIT AS DTI_MOTILICE,
      DT_FIM_LIC_TIT AS DTF_MOTICE,
      CD_TIP_PROV_COMIS           ,
      CD_CARGO_FUNCAO_COMIS AS CARGO_COMIS,
      CD_IDENT_CAT_FUNC_COMIS AS CATEG_COMIS,
      DT_POSSE_COMIS              ,
      DT_INIC_EXERC_COMIS         ,
      DT_INIC_SIT_ESP_COMIS AS SIT_ESP_COMIS,
      CD_IDENT_GRAU_NIV_COMIS     ,
      CD_UNID_ESC_CLASS_COMIS AS UE_C_COMIS,
      CD_UNID_ADM_CLASS_COMIS AS UA_C_COMIS,
      CD_UNID_ESC_EXER_COMIS AS UE_E_COMIS,
      CD_UNID_ADM_EXER_COMIS AS UA_E_COMIS,
      CD_TIP_INTERRUP_CESS_COMIS AS INTERRUP_COMIS,
      CD_MOT_INTERRUP_CESS_COMIS AS MOT_INTERRUP_COMIS,
      DT_INIC_INTERRUP_CESS_COMIS AS DTI_INTERRUP_COMIS,
      DT_FIM_INTERRUP_CESS_COMIS AS DTF_INTERRUP_COMIS,
      CD_MOT_AFAST_COMIS AS MOTIAFAS_COMIS,
      DT_INIC_MOT_AFAST_COMIS AS DTI_MOTIAFAS_COMIS,
      DT_FIM_MOT_AFAST_COMIS AS DTF_MOTIAFAS_COMIS,
      CD_MOT_LIC_COMIS AS MOTILICE_COMIS,
      DT_INIC_LIC_COMIS AS DTI_MOTILICE_COMIS,
      DT_FIM_LIC_COMIS AS DTF_MOTILICE_COMIS,
      CD_CARGO_FUNCAO_DESIGN AS CARGO_DESIGN,
      DT_INIC_DESIGN              ,
      CD_IDENT_REF_FAIXA_DESIGN AS REF_FAIXA_DESIGN,
      CD_IDENT_GRAU_NIV_DESIGN AS NIV_DESIGN,
      CD_UNID_ESC_CLASS_DESIGN AS UE_C_DESIGN,
      CD_UNID_ADM_CLASS_DESIGN AS UA_C_DESIGN,
      CD_MOT_SUBST_DESIGN         ,
      CD_TIP_INTERRUP_CESS_DESIGN ,
      CD_MOT_INTERRUP_CESS_DESIGN ,
      DT_INIC_INTERRUP_CESS_DESIGN,
      DT_FIM_INTERRUP_CESS_DESIGN ,
      CD_MOT_AFAST_DESIGN         ,
      DT_INIC_AFAST_DESIGN        ,
      DT_FIM_AFAST_DESIGN         ,
      CD_MOT_LIC_DESIGN           ,
      DT_INIC_LIC_DESIGN          ,
      DT_FIM_LIC_DESIGN           ,
      CD_IDENT_GRAU_NIV           ,
      CD_DIR_ENSI_ORG_CENTRAL     ,
      COD_CARGO                   ,
      COD_UNID_ADM                
FROM SAS.[082026].TB_FUNCIONAL
WHERE CD_SIT_REG = 'A' -- A = ATIVO, E = EXCLUÍDO , F = falecido, 0 = erro, P CATEGORIA P, I = INATIVO, B = BLOQUEADO
AND NR_CPF = '37243316816'
