

USE CEPEA_SAS

/*
INTERIOR	URE FRANCA 	20504	0	900667	35900667	64166	SUDARIO FERREIRA

SELECT top 10 *          
FROM ESCOLAS0826 
WHERE NOMEESC LIKE '%SUDARIO%'



SELECT DISTINCT
    ANO_TABELA,
    ANO_ULT_ALTERACAO,
    BD,
    ESQUEMA,
    TABELA,
    COLUNA,
    NUM_COLUNAS,
    NUM_LINHAS,
    END_COMPLETO
FROM [00_MAP]
WHERE END_COMPLETO LIKE '%ESCOLA%'  OR COLUNA LIKE '%ESCOLA%'
ORDER BY ANO_TABELA DESC, BD, ESQUEMA, TABELA DESC , COLUNA


*/

--1340


SELECT TOP 10 * FROM DB_CENSO_DESENVOLVIMENTO.[ColetaDados].[TB_DadosEscola] 
WHERE NomeCompletoEscola LIKE '%MATTATHIAS%'
OR NomeCompletoEscola LIKE '%SUDARIO FERREIRA%'

